// One-time generator for the globe's land dots (data/landDots.ts).
// Downloads Natural Earth 110m land (world-atlas TopoJSON) once, samples an
// evenly spaced grid on the sphere, and keeps the points that fall on land.
// The site never fetches anything: it only reads the generated file.
//   node scripts/flight-log/land-dots.mjs
import { writeFileSync } from "node:fs";

const STEP = 1.6; // degrees between dots, north–south
const topo = await (await fetch("https://cdn.jsdelivr.net/npm/world-atlas@2.0.2/land-110m.json")).json();

// TopoJSON arcs are quantized and delta-encoded.
const { scale, translate } = topo.transform;
const arcs = topo.arcs.map((arc) => {
  let x = 0, y = 0;
  return arc.map(([dx, dy]) => [(x += dx) * scale[0] + translate[0], (y += dy) * scale[1] + translate[1]]);
});
const ring = (ids) =>
  ids.flatMap((i, k) => {
    const pts = i < 0 ? [...arcs[~i]].reverse() : arcs[i];
    return k ? pts.slice(1) : pts;
  });
const polygons = topo.objects.land.geometries.flatMap((g) => (g.type === "Polygon" ? [g.arcs] : g.arcs)).map((p) => p.map(ring));

const inRing = (lon, lat, r) => {
  let inside = false;
  for (let i = 0, j = r.length - 1; i < r.length; j = i++) {
    const [xi, yi] = r[i], [xj, yj] = r[j];
    if (yi > lat !== yj > lat && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
};
const onLand = (lon, lat) => polygons.some(([outer, ...holes]) => inRing(lon, lat, outer) && !holes.some((h) => inRing(lon, lat, h)));

const dots = [];
for (let lat = -84; lat <= 84; lat += STEP) {
  // Fewer dots toward the poles so the spacing stays even on the sphere.
  const n = Math.max(1, Math.round((360 / STEP) * Math.cos((lat * Math.PI) / 180)));
  for (let k = 0; k < n; k++) {
    const lon = -180 + (k + 0.5) * (360 / n);
    if (onLand(lon, lat)) dots.push(+lat.toFixed(1), +lon.toFixed(1));
  }
}

writeFileSync(
  new URL("../../data/landDots.ts", import.meta.url),
  `// Generated by scripts/flight-log/land-dots.mjs from Natural Earth 110m land. Do not edit.
// Flat list of [lat, lon] pairs, one per dot on the globe.
export const landDots: number[] = [${dots.join(",")}];
`
);
console.log(`${dots.length / 2} land dots`);
