import type { Artifact as ArtifactT, MoodBoardConfig } from "./types";

// A single mood board tile (image, swatch, type specimen, or UI fragment).
export default function Artifact({ artifact, theme }: { artifact: ArtifactT; theme: MoodBoardConfig["theme"] }) {
  return (
    <figure className="mb-4 break-inside-avoid">
      <div
        className="overflow-hidden rounded-xl border"
        style={{ borderColor: theme.border, background: theme.surface, borderRadius: theme.radius }}
      >
        {artifact.kind === "image" ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={artifact.src} alt={artifact.alt} className="block w-full" loading="lazy" />
        ) : (
          artifact.content
        )}
      </div>
      <figcaption className="mt-2 flex items-center gap-1.5 text-xs" style={{ color: theme.muted }}>
        {artifact.generated && <span aria-label="generated by agent">✦</span>}
        {artifact.caption}
      </figcaption>
    </figure>
  );
}
